name: Npm Publish
on:
  release:
    types: [published]
jobs:
  build:
    name: Release on NPM

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.release.target_commitish }}
      - uses: actions/setup-node@v1
        with:
          node-version: 14
          registry-url: https://registry.npmjs.org/
      - run: git config --global user.email ""
      - run: git config --global user.name "Github Workflow"
      - run: npm version ${{ github.event.release.tag_name }}
      - run: yarn install
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_AUTH_TOKEN}}
      - run: git push
        env:
          github-token: ${{ secrets.GIT_TOKEN }}
